### ISSUE TITLE
Is dropping the 'PING' command by default a good idea?

### ISSUE THREAD

**Issue by matte-ek** [hburn7/BanchoSharp#4]
Hey. I noticed how bancho stopped sending me any messages after any brief inactivity from my side, so I did some digging. I had some suspicion that the client wasn't responding to any PING commands correctly, [details here](https://www.rfc-editor.org/rfc/rfc2812#section-3.7.2). In the default BanchoConfiguration, the PING command is included in the [array of IgnoredCommands](https://github.com/hburn7/BanchoSharp/blob/0cf07515c129ef65bc329d3adb6b10cab5bf89fa/BanchoSharp/BanchoClientConfig.cs#L49), which will of course cause the client to completely ignore this command and move on. Now the problem with that is that bancho will just think we're dead and drop our connection, without any further feedback.

I was just opening this issue to bring light to it, and just asking if maybe the client should deal with the PING command, and reply PONG, to make sure the connection isn't dropped.

**Comment by hburn7** [comment]
Hey there, thank you for pointing this out. I have been dealing with the same issue and thought it had something to do with `ListenerAsync()` getting stuck somewhere but this seems like a much better explanation for what has been going on (see [this issue](https://github.com/hburn7/Brigitta/issues/22)). I will implement a `PONG` response to these `PING`s in the next release and see if it helps with the connection drops.

**Comment by matte-ek** [comment]
No worries. I can now confirm that this is indeed the issue I was facing, and adding a quick `Execute("PONG")` for every `PING` command works fine. I could open a PR to address this, if you don't have any special way to implement this in mind.

**Comment by hburn7** [comment]
Perfect. No need on the PR, already on it. Thanks!
