### ISSUE TITLE
Events firing twice

### ISSUE THREAD

**Issue by mrmagic223325** [hburn7/BanchoSharp#52]
```csharp
public static async Task Main()
    {
        string username = "mr_magic223325";
        string password = "";
        IBanchoClient client = new BanchoClient(new BanchoClientConfig(new IrcCredentials(username, password), isBot: true));
        
        client.OnPrivateMessageReceived += Console.WriteLine;
    
        await client.ConnectAsync();
    }
```
If I send a message to BanchoBot the reply from it will fire the `OnPrivateMessageReceived` event twice.
![image](https://github.com/user-attachments/assets/acbc9e57-0868-4f8f-b73c-5ee190879396)

**Comment by matte-ek** [comment]
I can reproduce, seems to be a possible oversight from 13c59f7? Although I think Stage (repo owner) is using this version in his Brigitta application where I assume it's working fine. I should probably be dogfooding the library as well but I am on a slightly older version.

EDIT: Seems to be only used for alerts and such in Brigitta, possibly called twice there as well.

**Comment by hburn7** [comment]
Will look into this, thanks.

**Comment by hburn7** [comment]
Reproduced

**Comment by hburn7** [comment]
> I can reproduce, seems to be a possible oversight from [13c59f7](https://github.com/hburn7/BanchoSharp/commit/13c59f7f2a96a0b69a8ff34fa0199f5ec1cbd460)? Although I think Stage (repo owner) is using this version in his Brigitta application where I assume it's working fine. I should probably be dogfooding the library as well but I am on a slightly older version.
> 
> EDIT: Seems to be only used for alerts and such in Brigitta, possibly called twice there as well.

Yeah, I think that's it.
